apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: devopschallenge
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: app
          image: eminekibar/devopschallenge-backend:manual
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:11130"
          ports:
            - containerPort: 11130
          readinessProbe:
            httpGet: { path: "/", port: 11130 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/", port: 11130 }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

