apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: devopschallenge
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: >
    Host=postgres.devopschallenge.svc.cluster.local;
    Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD};
