apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devopschallenge
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31130